// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1a3PX40PcvpdayCH3-YkndDvkgMsnKo',
    appId: '1:12620033295:web:690e465395f0311be9a27a',
    messagingSenderId: '12620033295',
    projectId: 'community-waste',
    authDomain: 'community-waste.firebaseapp.com',
    storageBucket: 'community-waste.firebasestorage.app',
    measurementId: 'G-3LHGB5R18K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm59dfOa7DmB1AVvXPg7ZrQEKdd2v7DSI',
    appId: '1:12620033295:android:055304c404e522d2e9a27a',
    messagingSenderId: '12620033295',
    projectId: 'community-waste',
    storageBucket: 'community-waste.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3LtKD67YBMlZbdwaHlZzy_KO8xLmHIA',
    appId: '1:12620033295:ios:9ee40cd9ca2e52b5e9a27a',
    messagingSenderId: '12620033295',
    projectId: 'community-waste',
    storageBucket: 'community-waste.firebasestorage.app',
    iosBundleId: 'com.example.communityWasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3LtKD67YBMlZbdwaHlZzy_KO8xLmHIA',
    appId: '1:12620033295:ios:9ee40cd9ca2e52b5e9a27a',
    messagingSenderId: '12620033295',
    projectId: 'community-waste',
    storageBucket: 'community-waste.firebasestorage.app',
    iosBundleId: 'com.example.communityWasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH1a3PX40PcvpdayCH3-YkndDvkgMsnKo',
    appId: '1:12620033295:web:6fa27f405de797e6e9a27a',
    messagingSenderId: '12620033295',
    projectId: 'community-waste',
    authDomain: 'community-waste.firebaseapp.com',
    storageBucket: 'community-waste.firebasestorage.app',
    measurementId: 'G-5TF1JC1ZSM',
  );
}
